Vault backend
dockpack/ansible-vault pull request #135
Opened 2019-12-04 10:01 UTC by mourgaya

create VAULT_BACKEND variable

vault_backend: [-consul-]{+"{{ lookup('env','VAULT_BACKEND') | default('consul', true) }}"+}
vault_backend_consul: vault_backend_consul.j2
vault_backend_file: vault_backend_file.j2
vault_backend_etcd: vault_backend_etcd.j2

2020-03-13 16:02 UTC, bbaassssiiee commented
Purpose: allow to specify vault port and consul port and addr in case of multiple consul clusters in the same VLAN.

2020-03-14 14:20 UTC, bbaassssiiee requested changes
Please fix the typo in `consult_addr`.

2020-03-14 14:20 UTC, bbaassssiiee commented on defaults/main.yml
> +vault_consul: "{{consult_addr}}:{{consul_port}}"
`consult_addr` is a typo, should be `consul_addr`.

2020-09-30 09:07 UTC, rgarrigue commented on defaults/main.yml
> +consul_addr: "{{ lookup('env','CONSUL_ADDR') | default('127.0.0.1', true) }}"
Vault should be running on other servers than Consul.

2020-09-30 09:09 UTC, rgarrigue commented
Hi there. I'm coming around looking for something else : an option to enable disable_mlock. Since it's recommended for integrated storage (see https://www.vaultproject.io/docs/configuration#disable_mlock), maybe you can add it here ?

2020-09-30 12:58 UTC, bbaassssiiee commented on defaults/main.yml
> +consul_addr: "{{ lookup('env','CONSUL_ADDR') | default('127.0.0.1', true) }}"
... could be ... (with this PR)

2021-03-03 17:05 UTC, bbaassssiiee commented
Closing due to neglect by contributor.

2021-03-03 17:05 UTC, closed without merging