Add the possibility to enable vault commands to localhost
dockpack/ansible-vault pull request #140
Opened 2020-01-02 12:52 UTC by erbap

After looking to the error "Error initializing: Put http://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: connect: connection refused" I created a listener for localhost that could be enabled by a variable.

The default behavior is like before, without a listener for localhost.

2020-03-14 14:29 UTC, bbaassssiiee requested changes

2021-03-10 07:26 UTC, bbaassssiiee requested changes
please use the variable "{{ vault_port }}"

2021-04-02 20:08 UTC, bbaassssiiee commented
Please rebase your branch to include the Github action checks.

2021-06-24 13:26 UTC, bbayszczak commented
Your TCP listener is probably listening on the instance IP address that's why you cannot reach it using `127.0.0.1`

With this use case, setting `VAULT_ADDR` to your instance IP should solve your issue without having to add a new Vault TCP listener

2021-07-21 06:41 UTC, closed without merging