Recursively set TLS permissions
dockpack/ansible-vault pull request #166
Opened 2020-07-01 13:21 UTC by ilpianista

When `vault_tls_config_path` already exists and `vault_tls_copy_keys` is set to `false`, only the certificates root folder (`vault_tls_config_path`) get the correct permission while the certificates inside aren't touched.

2020-07-14 08:53 UTC, bbaassssiiee requested changes
Would setting the mode to 0700 complete this nice fix?

2020-07-18 13:27 UTC, ilpianista commented
> Would setting the mode to 0600 complete this nice fix?

Mmm, nope. `0600` isn't a valid mode for a folder.

2020-09-24 20:04 UTC, ilpianista commented
@bbaassssiiee Up

2020-09-29 13:51 UTC, bbaassssiiee commented
You're right! But let me rephrase please add a `mode:`, ansible-lint 4.3+ checks for that.

2020-09-29 14:17 UTC, ilpianista commented
Ok, it's a bit harder than that.

Since there's the `recurse` parameter, the `mode` that we specify are also applied to the files inside the folder. As workaround I could use a symbolic mode (e.g. `u=rwX,g=rX,o=rX`), but that will overwrite the permissions which are already set on the files if `vault_tls_copy_keys` is set to `false`.

I'm not sure what's the best thing to do here.

2020-10-07 14:57 UTC, bbaassssiiee commented
Group and others don't need access to TLS files.

2020-10-07 16:00 UTC, ilpianista commented
> Group and others don't need access to TLS files.

Exactly. If I use `mode: "u=rwX,g=rX,o=rX"` combined with `recurse: yes`, then group and others get access to them.

2020-10-07 16:04 UTC, ilpianista commented
To recap:
- if we only set `recurse: yes`, then ansible-lint complains
- if we set `recurse: yes` && `mode: 0755`, then the TLS files get the executable bit
- if we set `recurse: yes` && `mode: u=rwX,g=rX,o=rX`, then the TLS files are readable by `group` and `others`.

May I simply add a `skip_ansible_lint` tag to this task?

2020-12-23 15:41 UTC, bbaassssiiee commented
Adding `skip_ansible_lint` is Ok if the `mode:` works.

2022-11-15 12:23 UTC, bbaassssiiee commented
Too outdated

2022-11-15 12:23 UTC, closed without merging

2022-12-05 09:32 UTC, ilpianista commented
FTR: superseded by #306