Allow local installation to be performed as a privileged user
dockpack/ansible-vault pull request #168
Opened 2020-08-04 14:03 UTC by mhitza

Depending on the way the role is installed the local installation
steps will fail with a permission denied error.

Specifically I've encountered the issue in an Vagrant + Ansible Local
setup scenario, where the roles are installed using the pattern
described in the Vagrant docs:

https://archive.is/m8ZgO#install-galaxy-roles-in-a-path-owned-by-root

2020-08-14 12:56 UTC, bbaassssiiee commented
This role can be installed with [this Vagrantfile](https://github.com/dockpack/vault_dojo/blob/master/Vagrantfile)

2020-08-14 14:15 UTC, mhitza commented
> This role can be installed with [this Vagrantfile](https://github.com/dockpack/vault_dojo/blob/master/Vagrantfile)

You're using the ansible provider in that Vagrantfile, the issue is when using the ansible_local provider (roles are installed as root inside the VM)

2021-01-11 16:08 UTC, bbaassssiiee requested changes
I guess this is OK for this use-case, but can you please introduce a variable for this behaviour?

2021-01-18 12:01 UTC, mhitza commented
@bbaassssiiee let me know how you'd like that variable to be called. I can't think of a good name.

I guess it would be a variable that defaults to `false` and it's interpolated/expanded in the `become` directives I have commented out in my previous PR.

2021-01-18 15:07 UTC, bbaassssiiee commented
`vault_privileged_install`

2021-01-18 15:26 UTC, bbaassssiiee approved these changes
Thanks!

2021-01-18 15:26 UTC, merged