Fix some default values in README.md
dockpack/ansible-vault pull request #187
Opened 2020-12-23 00:30 UTC by DaazKu

Both default value are missing the hcl extension.

https://github.com/ansible-community/ansible-vault/blob/42ae6c7e5a8990b08f72c6b9a300d548b3e11c47/defaults/main.yml#L165
https://github.com/ansible-community/ansible-vault/blob/42ae6c7e5a8990b08f72c6b9a300d548b3e11c47/defaults/main.yml#L185

The source of this mistake was an oversight on the PR #153 that introduced the service registration feature

2020-12-23 15:30 UTC, bbaassssiiee requested changes
Thanks for spotting this. When I checked the files in templates I noticed that `templates/vault_service_registration_kubernetes.j2` is also missing that extension, and probably the `temlate:` action `src:` parameter needs to be adjusted as well to make this neat.

2020-12-23 15:55 UTC, DaazKu commented
> Thanks for spotting this. When I checked the files in templates I noticed that `templates/vault_service_registration_kubernetes.j2` is also missing that extension, and probably the `temlate:` action `src:` parameter needs to be adjusted as well to make this neat.

@bbaassssiiee There's no template/src because these files are included from the main template: https://github.com/ansible-community/ansible-vault/blob/master/templates/vault_main_configuration.hcl.j2#L53-L58

So the fix I just pushed should do it.

2021-01-18 15:23 UTC, bbaassssiiee approved these changes

2021-01-18 15:23 UTC, bbaassssiiee approved these changes

2021-01-18 15:23 UTC, bbaassssiiee commented
LFTM

2021-01-18 15:23 UTC, merged