Separate seal config files
dockpack/ansible-vault pull request #203
Opened 2021-01-21 19:28 UTC by willhaines

This splits out the AWS KMS and Azure Key Vault configurations into separate .hcl files, so that `vault_main.hcl` may be managed without providing KMS credentials every time.

This also limits updating the Google KMS credentials file to only when a source file is specified, for the same reason.

Note that it was also necessary to change the Vault command to read the entire `vault.d` configuration directory, rather than just the `vault_main.hcl` file. In my opinion, this is the expected behavior for a *.d configuration directory.

2021-01-24 15:37 UTC, bbaassssiiee commented
Rough idea: I think adding tags or extra-vars to certain actions can help, for instance to only run when wanted, of skipped in certain cases.

2021-01-25 18:53 UTC, willhaines commented
There were already variables to enable/disable the config sections that I moved into separate files, so I preserved that functionality. When we want to update our AWS KMS secrets, we run the following:

    export AWS_ACCESS_KEY_ID="<access key>"
    export AWS_SECRET_ACCESS_KEY="<secret access key>"
    export VAULT_AWSKMS_SEAL_KEY_ID="<key id>"
    
    ansible-playbook -K -e vault_awskms=true install.yml

To perform an upgrade or change other parts of the main config, we run the following (without the ENVs above set):
    
    ansible-playbook -K  install.yml

Where `install.yml` looks like this:

    ---
    hosts: vault_instances
    any_errors_fatal: true
    become: true
    become_user: root
    roles:
      - { role: brianshumate.vault, vault_backend: raft }


I'm certainly open to using tags as well, though. My current solution does not allow for deleting the `vault.d//vault_awskms.hcl` file.

2021-01-25 19:01 UTC, willhaines commented
If we added a tag, the interface could look something like this for AWS, and similar for Azure or Google.

To manage vault without touching KMS config:

    ansible-playbook -K  --skip-tags manage_kms install.yml

To update KMS secrets would be the same:

    export AWS_ACCESS_KEY_ID="<access key>"
    export AWS_SECRET_ACCESS_KEY="<secret access key>"
    export VAULT_AWSKMS_SEAL_KEY_ID="<key id>"

    ansible-playbook -K -e vault_awskms=true install.yml

To disable AWS KMS (deleting, or emptying `vault.d/vault_awskms.hcl`):

    ansible-playbook -K -e vault_awskms=false install.yml

I would prefer the opposite behavior  (have to explicitly enable a tag to manage KMS) to prevent accidentally wiping out the KMS config, but that would be a breaking change, and actually very easy for us to implement in our local `install.yml`.

2021-03-03 17:04 UTC, bbaassssiiee commented
Please rebase to include the molecule check in the PR.

2021-03-10 07:25 UTC, bbaassssiiee requested changes
Please rebase to include the molecule check in the PR.

2021-04-02 20:07 UTC, bbaassssiiee commented
The checks fail.

2021-04-06 20:37 UTC, bbaassssiiee approved these changes

2021-04-06 20:37 UTC, merged

2021-04-06 20:37 UTC, bbaassssiiee commented
Thanks!

2021-04-06 21:29 UTC, bbaassssiiee reviewed
Thanks for the heads up!