Add 'vault_use_config_path' for out-of-band configurations
dockpack/ansible-vault pull request #218
Opened 2021-03-27 21:34 UTC by kevinschoonover

Will update with issue description.

2021-04-02 20:05 UTC, bbaassssiiee requested changes
Please create 2 PRs, one with the style-changes as suggested by my review. And after that gets merged create the one with the config path changes. Please create an issue for that change.

2021-04-02 20:05 UTC, bbaassssiiee commented on defaults/main.yml
> +  - vault_address: "{{ vault_address }}"
I like these double quotes when there are "{{ moustache_variables }} or \n escapes",

2021-04-02 20:05 UTC, bbaassssiiee commented on defaults/main.yml
> +vault_gkms_project: ""
use single quotes when strings are 'literal values' or values with potential [gotchas](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#gotchas)!

Empty strings should be single-quoted IMHO.

2021-04-05 02:22 UTC, kevinschoonover commented
@bbaassssiiee should be fixed now. Let me know if there are any other issues!

2021-04-06 20:39 UTC, bbaassssiiee commented
There are conflicting files now, are you able to resolve these?

2021-04-08 07:44 UTC, bbaassssiiee approved these changes

2021-04-08 07:44 UTC, bbaassssiiee commented
Thanks!

2021-04-08 07:44 UTC, merged