add `when` based on a var for handler `Restart vault`
dockpack/ansible-vault pull request #234
Opened 2021-06-14 08:34 UTC by bbayszczak

Adding this condition will allow to choose if the playbook should be
able or not to restart the Vault service

Having this always on true on a production cluster could cause issues
because restarting all Vaults at the same time could end in a fully
sealed Vault cluster

2021-06-18 12:57 UTC, bbaassssiiee commented
Thanks for spotting this issue! Wouldn't `serial: 1` in the handler be better? Then they restart after eachother.

2021-06-21 07:29 UTC, bbaassssiiee requested changes, later dismissed

2021-06-21 07:29 UTC, bbaassssiiee commented on handlers/main.yml
> +  when: vault_service_restart | bool
Wouldn't serial: 1 in the handler be better? Then they restart after eachother.

2021-06-21 08:02 UTC, bbayszczak commented
Adding `serial: 1` will still restart each Vault one after another almost instantaneously add the end of the playbook.
The  problem will remain the same, all Vaults will ends up sealed at the same time

I added this change to control a possible downtime

Example when changing a configuration where a restart is needed (with the change proposed):
1. Start the playbook which push the configuration change without restarting any instance
2. Then, restart and unseal all non master instances, this will not cause any downtime as the master is still receiving requests
3. Perform a `step-down` operation which will switch the leader to another instance (which is already restarted and already has the new configuration)
4. Restart and unseal the last instance which wasn't restarted as it was previously the master

Without this change, at the end of step 1, all Vault instances are restarted and sealed, even with the `serial: 1`

Aven adding `serial: 1` at the play level won't help either, you'll have to hurry to unseal the Vault instance that have been restarted before the next one is restarted :)

2021-06-21 08:46 UTC, bbaassssiiee commented
Maybe a note like this in the README?

2021-06-21 09:08 UTC, bbayszczak commented
> Maybe a note like this in the README?

Sure, what do you want to clarify ?

2021-06-21 10:57 UTC, bbaassssiiee approved these changes

2021-06-21 10:57 UTC, merged