✨ Add `vault_gkms_copy_sa` var
dockpack/ansible-vault pull request #298
Opened 2022-06-20 09:16 UTC by fairglen

Var used to enable or disable the use of the default instance service account, on gcp kms auto-unseal 😉

Follows the same pattern/behavior as the [vault_gcs_copy_sa](https://github.com/ansible-community/ansible-vault#vault_gcs_copy_sa) var.

Also the default value makes it so that current uses of this role are not impacted 😉

2022-07-13 15:42 UTC, RCM7 commented
+1

2022-07-13 15:44 UTC, fairglen commented
@bbaassssiiee may I request a short review on this PR? Thank you. 🙏

2022-10-06 21:44 UTC, bbaassssiiee commented
Please resolve conflicts.

2022-10-06 21:45 UTC, bbaassssiiee requested changes
Please resolve conflicts

2022-10-06 21:46 UTC, bbaassssiiee requested changes
Please resolve conflicts

2022-10-27 16:26 UTC, fairglen commented
Done ✅  @bbaassssiiee 

> Please resolve conflicts

2022-10-27 17:47 UTC, bbaassssiiee approved these changes

2022-10-27 17:48 UTC, bbaassssiiee commented
This branch cannot be rebased due to conflicts.

2022-12-07 23:30 UTC, merged