support using already installed system certificates
dockpack/ansible-vault pull request #306
Opened 2022-10-03 08:22 UTC by mjourdan

Hosts on which we deploy Vault may already have keys and certificates provided by our certificate authority. As OS usually define separate paths for certificates and keys, this MR allows Vault to make use of them.

2022-10-03 09:15 UTC, bbaassssiiee commented
Your branch has conflicts

2022-10-03 09:16 UTC, bbaassssiiee requested changes
Conflicts in: `templates/vault_main_configuration.hcl.j2`

2022-10-03 09:32 UTC, mjourdan commented
Oops. Should be better now.

2022-10-10 12:06 UTC, mjourdan commented
@bbaassssiiee I just cleaned up the commits tree for easier review.

2022-10-10 12:29 UTC, bbaassssiiee approved these changes

2022-10-26 11:58 UTC, mjourdan commented
Thanks for the review, @bbaassssiiee. After your approval some checks failed because of missing dependencies, for both centos-7 and archlinux:

> Failed to find required executable \"rsync\"

Would it be possible to re-run the tests to get the branch merged?

2022-10-26 13:47 UTC, merged