improvements to TLS, encrypt gossip, enable hsm binary installs
dockpack/ansible-vault pull request #51
Opened 2018-06-01 18:12 UTC by drewmullen

Added CA file location to TLS listener in vault config

Added ability to enable TLS gossip between vault and consul

Cleaned up spacing on config file entries

Added vault enterprise download when the zip (and checksum) is not found locally. This will allow internally hosting rather than placing the file on the ansible local host

Enable installation of hsm binaries using bool vault_enterprise_premium_hsm var

Cleaned up some TLS var names for cleaner cert deployment. some file deployments were named as part of the path, this is confusing and easier to maintain when separated out.

2018-06-12 14:07 UTC, brianshumate requested changes
Thanks for the HSM bits here! I don't think we want to rename the `vault_backend` option though.

2018-06-12 14:07 UTC, brianshumate commented on defaults/main.yml
> +vault_backend_consul: vault_backend_consul.j2
This role currently supports both the Consul and File storage backends (and potentially others in the future); not sure this change makes sense.

2018-06-12 14:07 UTC, brianshumate commented on templates/vault_listener.hcl.j2
> +{% include vault_backend_consul with context %}
Same as above. Please leave this as-is.

2018-06-18 21:04 UTC, brianshumate commented
Thank you!

2018-06-18 21:04 UTC, merged

2018-06-19 19:44 UTC, drewmullen commented
you decide its okay to keep those changes to the vault_backend name?